### ISSUE TITLE
"Bis zum ersten, dessen Bedingung als falsch/wahr gewerte*t* wird."

### ISSUE THREAD

**Issue by tristanlins** [contao-community-alliance/merger2#1]

**Comment by zonky2** [comment]
@tristanlins what do you mean? or close comment...

**Comment by tristanlins** [comment]
I think there is or was a spelling mistake in the German translation ;-)

**Comment by zonky2** [comment]
Issue is open or you can close... or translate so dass man es versteht ;-)

**Comment by tristanlins** [comment]
-> #19
