### ISSUE TITLE
depth gibt Fehler aus, wenn "kleiner als"

### ISSUE THREAD

**Issue by Jugibur** [contao-community-alliance/merger2#10]
Gleich vorneweg:
Das "kleiner als"-Zeichen wird automatisch entfernt , wenn man kein Leerzeichen dahinter eingibt.

Wenn ich "depth(< 3)" eingebe (also mit Leerzeichen nach dem "<"), erscheint im Frontend der Fehler:
"Warning: Missing argument 1 for Bit3\Contao\Merger2\StandardFunctions::depth()..."

**Comment by dmolineus** [comment]
Kann ich für Contao 4.4 nicht reproduzieren. Sollte der Fehler dennoch noch auftreten, bitte entsprechenden Kommentar mit Schritte zur Reproduktion.
