### ISSUE TITLE
Kein Duplizieren bei „Inhalte“ möglich, um neuen Eintrag zu erstellen

### ISSUE THREAD

**Issue by Jugibur** [contao-community-alliance/merger2#13]
Im aktuellen Contao (3.3.0) hat ein Klicken auf den Duplizieren-Button keine Auswirkungen. Grundsätzlich funktioniert das Duplizieren in Contao 3.3.0.

**Comment by zonky2** [comment]
@Jugibur welchen "Duplizieren Button" meinst Du?

bitte mit aktuellem merger² und C3 testen

**Comment by zonky2** [comment]
wenn es um den Duplizieren Button beim FE-Modul geht (MCW) - das geht (C 3.5.35)

**Comment by dmolineus** [comment]
Schließe das Ticket mal. Falls das Problem nochmal auftritt, einfach ein neues aufmachen.
