### ISSUE TITLE
Manual/Handbuch

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/merger2#20]
Es braucht ein Manual/Handbuch... hier ins Wiki oder eigenes RTD? oder hat die CCA eine allgemeine RTD-Abteilung, wo man das mit reinsetzen kann...?

**Comment by dmolineus** [comment]
Reicht nicht die Readme aus, wie für die 4.0 angelegt? Kann bestimmt noch erweitert/ergänzt werden.

https://github.com/contao-community-alliance/merger2/blob/release/4.0.0/README.md

Außerdem erzeuge ich im Backend eine Übersicht aller Funktionen:

https://mobile.twitter.com/dvdmol/status/1026434914701459457/photo/1

Was denkst du?

**Comment by zonky2** [comment]
Hmmm… so eingängig finde ich die Beschreibung nicht – aber man kann das auch ins Wiki setzen (in DE + EN) inkl. ein paar Screenshots

 

Btw: https://github.com/contao-community-alliance/merger2/blob/release/4.0.0/README.md#rticleexistscolumn-string--includeunpublished-bool

Da fehlt ein „a“ von articleExist

 

Und ja – im BE das Verkehrsschild mit den „Rules“ wäre prima

 

Von: David Molineus [mailto:notifications@github.com] 
Gesendet: Montag, 6. August 2018 21:17
An: contao-community-alliance/merger2 <merger2@noreply.github.com>
Cc: zonky2 <info@e-spin.de>; Assign <assign@noreply.github.com>
Betreff: Re: [contao-community-alliance/merger2] Manual/Handbuch (#20)

 

Reicht nicht die Readme aus, wie für die 4.0 angelegt? Kann bestimmt noch erweitert/ergänzt werden.

https://github.com/contao-community-alliance/merger2/blob/release/4.0.0/README.md

Außerdem erzeuge ich im Backend eine Übersicht aller Funktionen:

https://mobile.twitter.com/dvdmol/status/1026434914701459457/photo/1

Was denkst du?

**Comment by dmolineus** [comment]
> Hmmm… so eingängig finde ich die Beschreibung nicht – aber man kann das auch ins Wiki setzen (in DE + EN) inkl. ein paar Screenshots

Die kann man gern noch weiter verbessern/ausbauen und ist als erster Schritt gedacht. Ich möchte eine Lösung, in der innerhalb von Contao dokumentiert wird. Es ist möglich eigene Funktionen hinzuzufügen. Für den Nutzer ist es dann sehr hilfreich, wenn er gleich sieht, welche Funktionen alle unterstützt werden.

Gleiches gilt für die verschiedenen Artikel-Module von Merger². Hier sollte es auch mit ins Backend rein. 

Natürlich kann man separat auch noch eine Doku pflegen. Persönlich habe ich nicht die Kapazitäten dazu. Klar könnte man ein Dokumentation auch in den docs Ordner des Repos legen. Ob rst basiert oder anders, ist dann ja zweitrangig. Nur, wer pflegt die? ;-)

> Da fehlt ein „a“ von articleExist

Danke, gefixt.

**Comment by dmolineus** [comment]
Ich habe nun die 4.0.0 released und die Doku in de Readme verlinkt.
