### ISSUE TITLE
Installationsproblem mit Contao 4.6.2

### ISSUE THREAD

**Issue by chriza** [contao-community-alliance/merger2#30]
merger2 wirft bei der Installation folgenden Fehler:

 Too few arguments to function ContaoCommunityAlliance\Merger2\EventListener
  \Hook\LoadFunctionExplanationsListener::__construct(), 0 passed in /www/htd
  ocs/wxxxxxxxx/kunden/xxxxxx/contao46/vendor/contao/core-bundle/src/Resour
  ces/contao/library/Contao/System.php on line 227 and exactly 2 expected

**Comment by dmolineus** [comment]
Should be fixed in release 4.0.3
