### ISSUE TITLE
Installation in Contao-4.6 nicht möglich

### ISSUE THREAD

**Issue by bizon1** [contao-community-alliance/merger2#31]
Die Installation von merger2 4.0 in Contao-4.6 bricht mit dieser Fehlermeldung ab:

`composer require contao-community-alliance/merger2
Using version ^4.0 for contao-community-alliance/merger2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing mobiledetect/mobiledetectlib (2.8.33): Downloading (100%)         
  - Installing suncat/mobile-detect-bundle (v1.1.1): Downloading (100%)         
  - Installing contao-community-alliance/merger2 (4.0.3): Downloading (100%)         
Writing lock file
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

In YamlFileLoader.php line 657:
                                                                               
  There is no extension able to load the configuration for "defaults" (in /da  
  tadisk/www/mlp2/vendor/contao-community-alliance/merger2/src/DependencyInje  
  ction/../Resources/config/listener.yml). Looked for namespace "defaults", f  
  ound none                                                                    
                                                                               

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

                                                                                                   
  [RuntimeException]                                                                               
  An error occurred while executing the "contao:install-web-dir" command:                          
  In YamlFileLoader.php line 657:                                                        
                                                                                   
    There is no extension able to load the configuration for "defaults" (in /da    
    tadisk/www/mlp2/vendor/contao-community-alliance/merger2/src/DependencyInje    
    ction/../Resources/config/listener.yml). Looked for namespace "defaults", f    
    ound none 
`

**Comment by dmolineus** [comment]
Omg, thanks. Fixed with 9a9803ef4eabd60e9f900d955b15eb3833c73b88 and released as 4.0.4. Shouldn't try to fix isses at late night...
