### ISSUE TITLE
[FR] Inhalte um die Auswahl eines Contentelementes erweitern

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/merger2#33]
Inhalte um die Auswahl eines Contentelementes erweitern

**Comment by dmolineus** [comment]
Kannst du dies etwas näher spezifizieren, was du möchtest?

**Comment by zonky2** [comment]
Aktuell kann man nur einen kompletten Artikel (oder ein Modul) als Element anzeigen - schön wäre, wenn man auch ein Inhaltselement auswählen könnte - dann muss ich nicht immer einen ganzen Artikel anlegen mit einem CE um das einsetzen zu können

**Comment by dmolineus** [comment]
Bisher gibt es im Merger² nur die Möglichkeit Module selbst zu referenzieren. Die Artikel werden ja in erweiterter Form wie von Contao geladen - sprich wie durch ModuleArticle - halt nur mit der Vererbung.

Eine Referenzierung einzelner Artikel/Inhaltselemente gibt es so ja nicht. Mit hofff/contao-content gibt es bereits eine Erweiterung, mit dem man Artikel referenzieren kann. Einzelne Inhaltselemente lassen sich im mit dem HTML-Modul und dem InsertTag referenzieren.

Zusammengefasst sehe ich nicht die Notwendigkeit dieses Featzre im merger² zu unterstützen.
