### ISSUE TITLE
Bedingungen funktionieren nicht mit &&

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/merger2#35]
Ich will ein Modul nur anzeigen lassen, wenn ich in bzw. unterhalb von zwei bestimmten Seiten bin.
Ich habe dazu `pageInPath(3)` und `pageInPath(26)` per && verknüpft: `pageInPath(3) && pageInPath(26)` wie im Beispiel von dir gezeigt. Leider funktioniert das nicht und ich bekomme keine Ausgabe oder ich bekomme das auch angezeigt, wenn es nicht angezeigt wird. Ich habe jetzt erst mal alles doppelt definiert (geht, ist aber unschön und etwas viel arbeit *g*).

Viele Grüße

**Comment by dmolineus** [comment]
Funktioniert denn `pageInPath(3) & pageInPath(26)` oder `pageInPath(3) and pageInPath(26)`?

**Comment by MacKP** [comment]
Funktioniert leider beides nicht.

Viele Grüße

**Comment by MacKP** [comment]
Wenn ich mich gerade nicht irre, dann funktioniert aber die umkehrung mit &&:
`!pageInPath(3) && !pageInPath(26)`

Viele Grüße

**Comment by dmolineus** [comment]
Dann ist deine Logik falsch. :-)

Du willst wahrscheinlich ein logisches Oder verwenden: `pageInPath(3) || pageInPath(26)`. 

Zeige das Modul an, wenn sich im aktuellen Seitenpfad die ID  `3` **oder *26* beinhaltet.

**Comment by MacKP** [comment]
OMG.. du hast natürlich recht... Ich schließe dann mal schnell das Ticket ;-)
Danke!
