### ISSUE TITLE
Internal Server Error mit Contao 4.8-RC2

### ISSUE THREAD

**Issue by chriza** [contao-community-alliance/merger2#36]
Hallo,

ich habe mir eine Testinstallation für Contao 4.8-RC2 angelegt und darin merger2 installiert.
Nach Absenden des BE-Login Formulares erscheint folgende Meldung:

![grafik](https://user-images.githubusercontent.com/1572887/62273217-44b18480-b43d-11e9-8fba-3d23ce8e5072.png)

**Comment by dmolineus** [comment]
Contao 4.8 removes the twig template engine from the default enabled one (see contao/contao@d42ccf4#diff-eb1e91aff34b45d3a19eab09c406aa06L21-L22).

We have to reanable it again or just use twig directly.

**Comment by dmolineus** [comment]
Branch hotfix/4.0.6 contains the bugfix. Would be great if you could confirm that it works in your environment (See #37)

**Comment by chriza** [comment]
Hallo,

wie kann ich den Branch 4.0.6 mit dem contao-manager installieren? Packagist zeigt ihn nicht an.

**Comment by dmolineus** [comment]
Branches erhalten einen `dev-` Prefix. Also steht der Branch über die Versionsanforderung `dev-hotfix/4.0.6` zur Verfügung.

**Comment by chriza** [comment]
Beim Erstellen eines Seitenlayouts tritt folgender Fehler auf:
![grafik](https://user-images.githubusercontent.com/1572887/63414388-0be14b80-c3fc-11e9-8ac6-2f35d9948ce4.png)
Außer merger2 ist keine weitere Extension installiert.

**Comment by dmolineus** [comment]
Merger² installiert den Milticolumnwizard und dieser den Translator, der noch einen Bug hat.

https://github.com/contao-community-alliance/translator/pull/9

Wird der Translator explizit mit der Versionsangabe `dev-hotfix/2.1.3 as 2.1.3` installiert, sollte das Problem behoben sein.

**Comment by chriza** [comment]
Vielen Dank, der merger2 läuft.

**Comment by dmolineus** [comment]
Fixed with 4.0.6. contao-community-alliance/translator fix is also released.
