### ISSUE TITLE
 non-existent service "templating"

### ISSUE THREAD

**Issue by mpunkt** [contao-community-alliance/merger2#38]
Das Update Contao 4.7 nach 4.8 scheitert mit folgendem Fehler:

> The service "ContaoCommunityAlliance\Merger2\EventListener\Hook\LoadFunctionExplanationsListener" has a dependency on a non-existent service "templating".

Ich denke #37 könnte die Lösung sein. Wie installiert man per composer den hotfix 4.0.6?

**Comment by dmolineus** [comment]
See #36.

**Comment by mpunkt** [comment]
Alles gut! Danke.
