### ISSUE TITLE
Contao 3.1.RC1 needs autoload "register_classes = true"

### ISSUE THREAD

**Issue by adressler** [contao-community-alliance/merger2#4]
Without registered classes in autoload.php, Merger2 2.2.1 is not compatible with Contao 3.1.RC1.
System log entry is:  Module class "" (module "Merger2") does not exist.

After setting register_classes to true and updating autoload, the module works fine.

**Comment by zonky2** [comment]
@adressler please check the current merger² and C3 LTS
