### ISSUE TITLE
Artikel können nicht bearbeitet werden, wenn ein Merger2 Modul mit der Funktion articleExists eingebunden ist.

### ISSUE THREAD

**Issue by chriza** [contao-community-alliance/merger2#44]
Contao 4.11.2 und Contao 4.11.3

Wenn ein Modul mit einer Bedingung articleExists erstellt und im Seitenlayout eingebunden wird, kann auch ein Administrator keine Artikel mehr bearbeiten. 
Screenshots:
![grafik](https://user-images.githubusercontent.com/1572887/118171816-f14ed180-b42b-11eb-9f4b-1803d319a562.png)
![grafik](https://user-images.githubusercontent.com/1572887/118171847-f90e7600-b42b-11eb-9fd9-eeaab5ec4947.png)
![grafik](https://user-images.githubusercontent.com/1572887/118171868-ff045700-b42b-11eb-98c8-fa2f635d9bfe.png)

PS: Ich finde es sehr bedauerlich, dass mit Contao 4.11.2 keine Root-Artikel mehr erstellt werden können. Mit Contao 4.11.1 konnte ich zum ersten Mal die Funktionen "Artikel von Elternseite bis zur Wurzel erben" und "Artikel der Seite oder Artikel von Elternseite bis zur Wurzel erben" nutzen.

**Comment by dmolineus** [comment]
Den Fehler kann ich nicht reproduzieren. Mit merger² 4.3.0 ist es möglich in Root-Seiten Artikel anzulegen.
