### ISSUE TITLE
Installation in Contao 4.11 und php 8 nicht möglich

### ISSUE THREAD

**Issue by gmoelter** [contao-community-alliance/merger2#45]
Die Installation bricht mit Fehlermeldung ab:

> Your requirements could not be resolved to an installable set of packages.
> Problem 1
>    - contao-community-alliance/merger2 4.2.0 requires ext-json ~1.2 -> it has the wrong version (8.0.7) installed. Install or enable PHP's json extension.
>   - contao-community-alliance/merger2[4.2.1, ..., 4.2.2] require symfony/config ^3.0 || ^4.0 -> found symfony/config[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.25] but the package is fixed to v5.2.10 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>    - Root composer.json requires contao-community-alliance/merger2 ^4.2 -> satisfiable by contao-community-alliance/merger2[4.2.0, 4.2.1, 4.2.2]`

**Comment by dmolineus** [comment]
You need to update all dependencies as long as symfony 5 is not offically supported by this package.
