### ISSUE TITLE
Plugin maintained and ready for Contao 5

### ISSUE THREAD

**Issue by Metis77** [contao-community-alliance/merger2#53]
I was just wondering if this beautiful plugin is still maintained and ready for Contao 5 and PHP8?

If not, any suggestions for an alternative?

**Comment by zonky2** [comment]
It should work under PHP8 - there is also a small fix for this https://github.com/contao-community-alliance/merger2/pull/52

For Contao 5 a new version would have to be created - so far nobody has been found who has created a corresponding PR or brought in a sponsorship for it.

**Comment by Metis77** [comment]
Any guess, how much sponsorship would be needed?

**Comment by zonky2** [comment]
The number of sponsors is not decisive - the total amount is ;-)

You would have to install it under C5 and see where it gets stuck.

I estimate half a working day to one working day.

**Comment by zonky2** [comment]
Dev should run at Contao 5
https://github.com/contao-community-alliance/merger2/tree/develop

**Comment by dmolineus** [comment]
Version 4.3.1 is ready for Contao 5 now.
