### ISSUE TITLE
bei "vererbter Vererbung" Speicherüberlauf 

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/merger2#6]
...da es in der Community keine weiteren Infos gab, hier ein Ticket...

ich habe merger² mal in der Vererbungsfunktion eingesetzt - funktioniert prächtig, bis auf Seiten in der dritten Ebene... hier rödelt PHP so lange, bis der Speicher voll ist => exhaust memory

Vererbt wird der Inhalt der "rechten Spalte" als Artikel
1. Seite - Rechts: Include-Inhaltselement
   1.1 Seite - Rechts: Modul Vererbung
   1.1.1 Seite - Rechts: Modul Vererbung

... ich kann das Include-CE auch auf die Unterseiten packen - mit dem Vererben muss man sich nicht weiter kümmern wenn auf Ebene 1 was geändert wird oder die (Unter)Seite umzieht

C: 3.1.5 + merger2 2.3.1 stable 6 

https://community.contao.org/de/showthread.php?47347-merger%B2-bei-quot-vererbter-Vererbung-quot-Speicher%FCberlauf

**Comment by dmolineus** [comment]
Vermute eine Endlosschleife. Lässt sich dies im Jahre 2018 noch reproduzieren?

**Comment by zonky2** [comment]
werde ich testen...

**Comment by zonky2** [comment]
Test:
* FE-Modul "Merger²" angelegt - "Artikel von Elternseite bis zur Wurzel erben"
* FE-Modul im Seitenlayout in Hauptspalte (kann auch Seite sein..)
* 1. Seite mit Include-Inhaltselement (Vererbung eingeschaltet bei Artikel)
* 2. Seite als Kind sowie noch vier weitere jeweils als Kind - mit Artikel aber kein CE

Test in FE: bis in 5. Unterebene wurde der Text angezeigt - Achtung: nur Typ "Artikel von Elternseite erben" reicht nicht - da wird der Text nur auf der Zweiten Seite angezeigt

![screenshot_182](https://user-images.githubusercontent.com/1045318/43727847-6de83002-99a3-11e8-8319-16d1348d7e2f.jpg)
