### ISSUE TITLE
Merger² Version 3.0.0 Update throws Errors by and condition & children function bug

### ISSUE THREAD

**Issue by dev4web** [contao-community-alliance/merger2#7]
I just updated tody the merger² module in my contao 3.2.7 installation and the following combination children(>0) & depth(4) throws the following:

Fatal error: Uncaught exception Bit3\Contao\Merger2\Constraint\Parser\ParserException with message Invalid token, expect a "word" character got > thrown in system/modules/merger2/classes/src/Bit3/Contao/Merger2/Constraint/Parser/InputStream.php on line 218

Are there some syntax changes?

**Comment by dmolineus** [comment]
I cannot reproduce the issue at the current branch release/4.0.0. Changing the compare operator in the children function is supported now (See c947300).
